# Give super user permissions
sudo: required

# Install docker
services:
  - docker

# build an image from Dockerfile.dev and use local directory
before_install:
  - docker build -t hermaze/docker-react -f Dockerfile.dev .

# Series of commands for test execution
script:
  - docker run hermaze/docker-react npm run test -- --coverage

# send to aws to deploy
deploy: 
  provide: elasticbeanstalk
  region:  "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-746451450635"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
